### ISSUE TITLE
JideFX and Scene Builder

### ISSUE THREAD

**Issue by wattsie** [jidesoft/jidefx-oss#15]
G'day,
  Would anyone able to point me in the right direction. I have been trying to use JideFX with Scene Builder 2 generated FXML files.

  It is probably a stupid question... but I'll ask anyway. Sorry if it is out of order.

  What is the best method to enable JideFX validation and decoration on a textfield added using SB2?

  I understand you need to use "new DecorationPane(pane)" , however, if the pane is generated within SB2, and embedded within other Pane's how would one go about called the DecorationPane method? 

  I can easily embed the validation within the fxml's controller and I know this works well.

  And, If I load the FXML file manually, and wrap the pane within DecorationPane it works and the decorations show when fields are invalid, 

  Where I am coming unstuck, is I would like to be able to design the GUI within SB2.

  Any pointers would be very appreciated.

  Thanks in advance.

  PS:Understand if it is not easy, and I have to revert to manually coding the GUI, but it would be so much easier if there was a simple way to do this within SB2.

Cheers.

**Comment by aalmiray** [comment]
Better integration with FXML also discussed at #30. Other components may need a facelift too.
