### ISSUE TITLE
Disable jar signing on local install

### ISSUE THREAD

**Issue by eiswind** [jidesoft/jidefx-oss#42]
Well, I have no clue about gradle, but I had a hard time building the project locally as it wants to sign the jars on local install. Probably life would be easier when you do this on deploy only?

**Comment by jidesoft** [comment]
Gradle is pretty popular. We probably won't introduce a new build system other than gradle for a while so you may have it setup on your computer, not just for this project but also useful for many other projects.

**Comment by eiswind** [comment]
Yes thats what I did. But not beeing used to gradle this took me another 30minutes before getting up the project. Was just a suggestion to turn it off on local install. But feel free to close it if you don't bother :)

**Comment by jidesoft** [comment]
I see. I didn't even notice it signs the jar to be frank. I'l see if I can figure out a way to make it obvious.
