### ISSUE TITLE
gradle build failure

### ISSUE THREAD

**Issue by mahadevshindhe** [jidesoft/jidefx-oss#45]
C:\mydrive\documents\JavaFx\jidefx-oss-master>gradle
Defining custom æbuildÆ task is deprecated when using standard lifecycle plugin has been deprecated and is scheduled to be removed in Gradle 3.0
:initExamples UP-TO-DATE
:initProjectFiles UP-TO-DATE
:jidefx-common:compileJava
C:\mydrive\documents\JavaFx\jidefx-oss-master\module-common\src\main\java\jidefx\utils\FXUtils.java:23: error: cannot find symbol
import com.sun.javafx.Utils;
                     ^
  symbol:   class Utils
  location: package com.sun.javafx
C:\mydrive\documents\JavaFx\jidefx-oss-master\module-common\src\main\java\jidefx\utils\FXUtils.java:42: error: cannot find symbol
        final Screen currentScreen = Utils.getScreenForPoint(point.getX(), point.getY());
                                     ^
  symbol:   variable Utils
  location: class FXUtils
C:\mydrive\documents\JavaFx\jidefx-oss-master\module-common\src\main\java\jidefx\utils\FXUtils.java:43: error: cannot find symbol
        return Utils.hasFullScreenStage(currentScreen) ? currentScreen.getBounds() : currentScreen.getVisualBounds();
               ^
  symbol:   variable Utils
  location: class FXUtils
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
:jidefx-common:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':jidefx-common:compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.858 secs

C:\mydrive\documents\JavaFx\jidefx-oss-master>

**Comment by jidesoft** [comment]
We currently are not actively working on it so please feel free to change the code and push the change. I will commit it. The error looks like we used a private API. See if you can find a replacement for it.
